[package]
name = "tlsproxy_rs"
version = "1.0.1"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4.3.10", features = ["derive"] }
bytesize = {version = "1.1.0", features = ["serde"]}
chrono = "0.4.26"
regex = "1.8.4"
serde_json = "1.0.99"
futures = "0.3.28"
log4rs = { version="1.2.0", features = ["gzip", "background_rotation"] }
log = "0.4.19"
serde = "1"

[[bin]]
name="tlsproxy"
path="src/main.rs"

[[bin]]
name="test"
path="src/test.rs"
