listeners:
  SSH:
    bind: 0.0.0.0:1443
    target_port: 1443
    policy: DENY
    rules:
      static_hosts: []
      patterns:
      - ^www.g.*$
    max_idle_time_ms: 3600000
    speed_limit: 0.0
  '1443':
    bind: 0.0.0.0:2443
    target_port: 443
    policy: DENY
    rules:
      static_hosts: []
      patterns: []
    max_idle_time_ms: 3600000
    speed_limit: 10240000.0
  aaaa:
    bind: 0.0.0.0:17877
    target_port: 443
    policy: DENY
    rules:
      static_hosts: []
      patterns: []
    max_idle_time_ms: 3600000
    speed_limit: 0.75
options:
  log_config_file: log4rs.yaml
  self_ips:
  - 127.0.0.1
  - me.jungle
dns:
  home.wushilin.net: 192.168.44.100
admin_server:
  bind_address: 0.0.0.0
  bind_port: 48888
  username: admin
  password: pass1234
  tls_cert: null
  tls_key: null
  tls_ca_cert: null
  mutual_tls: null
  tls: false
  rocket_log_level: critical
