listeners:
  '1443':
    bind: 0.0.0.0:1443
    target: ''
    target_port: 443
    policy: DENY
    rules:
      static_hosts: []
      patterns: []
    max_idle_time_ms: 3600000
    speed_limit: 0.0
    mode: terminate
    upstream_tls: true
  test80:
    bind: 0.0.0.0:1080
    target: www.google.com:443,www.baidu.com:443
    target_port: 80
    policy: DENY
    rules:
      static_hosts: []
      patterns: []
    max_idle_time_ms: 3600000
    speed_limit: 0.0
    mode: forward
    upstream_tls: true
options:
  runtime_dir: ./runtime
dns:
  exact:
  - from: home.wushilin.net
    to: 192.168.44.100
  - from: aa
    to: aaaa
  suffix:
  - from: .abc.com:443
    to: 127.0.0.1:443
  regex:
  - hostname: aaaa
    port: 444
    to: 192.168.44.100
ca:
  localca:
    ca_cert: local_ca/CA.pem
    ca_key: local_ca/CA.key
    working_dir: local_ca
admin_server:
  bind_address: 0.0.0.0
  bind_port: 48888
  username: admin
  password: pass1234
  tls: true
  san:
  - localhost
  - 127.0.0.1
  - ::1
